Updated channel and ifo submission format
ML4GW/aframe pull request #291
Opened 2024-10-16 20:48 UTC by wbenoit26

Changes the way that ifo and channel information is formatted in our gracedb submissions to align with what Alex and Roberto are requesting. I need the gracedb PR to be merged before I can test this.

2024-10-17 14:35 UTC, EthanMarx commented
Looks good - have tested submitting with this to GraceDB?

2024-10-30 15:45 UTC, wbenoit26 commented
@EthanMarx I tested this out and the format is showing up as expected: [https://gracedb-test.ligo.org/events/G1188124/view/](https://gracedb-test.ligo.org/events/G1188124/view/)

2024-10-30 16:02 UTC, EthanMarx commented on projects/online/config.yaml
> +channel: ["H1:GDS-CALIB_STRAIN", "L1:GDS-CALIB_STRAIN"]
I think this should be `channels`

2024-10-30 16:02 UTC, EthanMarx requested changes
One nit pick on the config. looks great

2024-10-30 16:10 UTC, wbenoit26 commented on projects/online/config.yaml
> +channel: ["H1:GDS-CALIB_STRAIN", "L1:GDS-CALIB_STRAIN"]
Good catch, fixed

2024-10-30 16:12 UTC, merged