Tuning clean up
ML4GW/aframe pull request #299
Opened 2024-10-30 19:52 UTC by EthanMarx

- Integrating with the latest `lightray` update which now exposes most of the `tune.Tuner` API. This will allow users to configure things like the `TrialScheduler`, `SearchAlg` etc.
- Adds `TuneLocal` task which works the same way as `TrainLocal` vs `TrainRemote`: If `AFRAME_TRAIN_RUN_DIR` is an s3:// path will tune remotely.
- Removes `TraceModel` callback, which was unnecessary to do at the end of every epoch for every trial, and was contributing to some bottlenecks. Don't yet have a cleaner solution for automatically tracing the best model, so will have to do it by hand for now.

2024-10-30 22:28 UTC, wbenoit26 commented on projects/train/configs/bns.yaml
> +  enable_progres_bar: true
I'm guessing this should be "progress"?

2024-10-30 22:31 UTC, wbenoit26 requested changes
Looks good, I think there's just a typo in `bbh.yaml` and `bns.yaml`

2024-10-30 22:38 UTC, EthanMarx commented on projects/train/configs/bns.yaml
> +  enable_progres_bar: true
yup

2024-10-30 22:43 UTC, wbenoit26 submitted a review, later dismissed

2024-10-30 22:58 UTC, EthanMarx commented
> Looks good, I think there's just a typo in `bbh.yaml` and `bns.yaml`

What was the typo in `bbh.yaml`?

2024-10-30 23:02 UTC, wbenoit26 commented
I thought it was also "progres" instead of "progress", but it looks like I misread it, or just looked at `bns.yaml` twice

2024-10-31 12:47 UTC, EthanMarx commented
@wbenoit26 can I get an approval when you get a chance?

2024-10-31 13:18 UTC, merged